version: '3.8'

services:
  app:
    build: .
    ports:
      - "50051:50051"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=task_manager
      - SERVER_PORT=50051
    depends_on:
      - db
    restart: on-failure

  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=task_manager
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: